import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
    translation: {
      nav: { translate: "Translate", files: "Files", history: "History", glossaries: "Glossaries", prompts: "Prompts", providers: "AI providers", settings: "Settings", logs: "Logs" },
      common: { save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", add: "Add", close: "Close", import: "Import", export: "Export", name: "Name", test: "Test", testing: "Testing...", enabled: "Enabled", disabled: "Off", select: "Select", none: "None", ready: "Ready", error: "Error", retry: "Retry", openMenu: "Open menu", closeMenu: "Close menu", productSubtitle: "AI translation studio", noModel: "No model" },
      translate: { title: "Translate text", subtitle: "Translate with a selected AI, prompt and terminology set.", source: "Source", target: "Translation", sourceLanguage: "Source language", targetLanguage: "Target language", detect: "Auto detect", swapLanguages: "Swap source and target languages", provider: "AI provider", prompt: "Prompt", glossaries: "Glossaries", reasoning: "Reasoning effort", reasoningNone: "None", reasoningLow: "Low", reasoningMedium: "Medium", reasoningHigh: "High", placeholder: "Enter or paste text", action: "Translate", working: "Translating...", copy: "Copy result", copied: "Copied", characters: "{{count}} chars" },
      files: { title: "Translate files", subtitle: "Document structure and formatting are retained where the format permits.", drop: "Drop a file here or choose a file", supported: "PDF, DOCX, PPTX, XLSX, TXT, Markdown, HTML, CSV, JSON, SRT, VTT, PNG, JPG and WebP", choose: "Choose file", action: "Translate file", working: "Submitting...", summarize: "Summarize before translating", cancel: "Cancel translation", cancelling: "Cancelling...", waitingForQueue: "Waiting for the file queue", download: "Download translation", downloading: "Downloading...", downloadComplete: "Download complete", savedTo: "Saved to {{path}}", openFile: "Open file", openFolder: "Open folder", mode: "Output format", translatedOnly: "Translation only", bilingual: "Original + translation", jobs: "Translation jobs", progress: "Progress", queued: "Queued", preparing: "Preparing", summarizing: "Summarizing", translating: "Translating", packing: "Building file", completed: "Completed", failed: "Failed", cancelled: "Cancelled", segments: "{{done}} / {{total}} segments", batches: "{{done}} / {{total}} batches", skipped: "{{count}} skipped", partialWarning: "{{count}} segments were not translated", retryFailed: "Retry failed batches", retryFile: "Retry file", retryFileHint: "The file translation failed before a result was created.", retrying: "Retrying...", streaming: "Live output", noJobs: "No file jobs", downloadBusy: "File is not ready", refresh: "Refreshing" },
      glossary: { title: "Glossaries", subtitle: "Apply one or more terminology sets to each translation.", new: "New glossary", empty: "No glossaries yet", entries: "{{count}} terms", sourceTerm: "Source term", targetTerm: "Preferred translation", note: "Note", addTerm: "Add term", sourceLanguage: "Source language", targetLanguage: "Target language" },
      prompt: { title: "Prompts", subtitle: "Reusable instructions control tone, audience and formatting.", new: "New prompt", empty: "No prompts yet", content: "Instructions", variables: "Available variables: {{source_language}}, {{target_language}}, {{glossary}} and {{text}}." },
      provider: { title: "AI providers", subtitle: "Configure OpenAI-compatible AI services.", new: "Add provider", type: "Provider type", baseUrl: "OpenAI-compatible API base URL", model: "Model", apiKey: "API key", apiKeyHint: "Stored only on this device", proxyMode: "Proxy", proxyNone: "Do not use a proxy", proxySettings: "Use the proxy configured in Settings", proxySystem: "Use the system proxy", images: "Supports image input/output", connected: "Provider responded successfully", compatibilityHint: "Enter the API base URL ending in /v1, for example http://127.0.0.1:8000/v1. Text requests support both /responses and /chat/completions; image generation still requires /responses.", reasoningParser: "Reasoning parser", reasoningParserAuto: "Auto (from model name)", reasoningParserHint: "For vLLM, choose the same parser used by --reasoning-parser. Auto recognizes mainstream Qwen, DeepSeek, GLM, Gemma and Granite models.", discoverModels: "Discover models", discovering: "Discovering...", contextSize: "Context size (tokens)", contextUnit: "tokens", contextSizeHint: "Used to derive the default file batch character budget.", maxSegments: "Max segments per batch", segmentsUnit: "segments", maxSegmentsHint: "Maximum independent segments sent in one file request.", maxConcurrent: "Max concurrent requests", concurrentUnit: "concurrent", maxConcurrentHint: "Maximum file requests this model may process at once.", textTranslationModel: "Commonly used models for text translation", textTranslationModelHint: "When enabled, file translation leaves one request slot available for text translation." },
      settings: { title: "Settings", subtitle: "Network, language, downloads and local web access.", language: "Interface language", proxy: "Proxy URL", proxyHint: "HTTP, HTTPS, SOCKS5 or SOCKS5H. Leave empty for a direct connection.", webAccess: "Web access", address: "Listening address", port: "Port", webHint: "Restart Tranova after changing the web address.", downloads: "Downloads", downloadLocation: "Download location", downloadLocationHint: "Choose where completed file translations are saved on desktop.", sourceFolder: "Original file folder", systemDownloads: "System Downloads folder", customFolder: "Custom folder", customFolderHint: "Used when the custom folder option is selected.", customFolderPlaceholder: "Enter a folder path", chooseFolder: "Choose folder", autoDownload: "Automatically download completed files", autoDownloadHint: "Save the translated file as soon as translation finishes.", askDownload: "Ask for download location", askDownloadHint: "Use the last selected location as the default in the save dialog.", enabledOption: "Enabled", ai: "AI requests", timeout: "AI request timeout (seconds)", timeoutHint: "Maximum wait for a non-streaming request, or for the next chunk of a streaming response. The stream timer restarts whenever data is received.", logging: "Application logging", loggingHint: "Store system events and AI conversations for the Logs page.", logLevel: "Minimum log level", logLevelHint: "Only messages at this level or above are stored.", version: "Version", restart: "Server address changes take effect after restart." },
      history: { title: "Translation history", subtitle: "Review recent text and file translation jobs.", empty: "No translation history yet", clear: "Clear history", remove: "Remove from history", source: "Source", translation: "Translation", file: "File", text: "Text", segments: "File translation" },
      logs: { title: "Logs", subtitle: "Inspect application events and AI conversations.", system: "System logs", conversations: "AI conversations", empty: "No logs yet", success: "Success", failure: "Failed", request: "Request", response: "Response" },
      status: { backendUnavailable: "Tranova service is unavailable. Start the desktop app or server.", noProvider: "Configure and enable an AI provider first.", saved: "Saved", imported: "Imported successfully" },
      languages: { en: "English", zh: "简体中文", "zh-CN": "简体中文", "zh-TW": "繁體中文", ja: "日本語", ko: "한국어", fr: "Français", de: "Deutsch", es: "Español", ru: "Русский", ar: "العربية", tlh: "tlhIngan Hol", "火星文": "吙煋呅", auto: "Auto detect", customPlaceholder: "Enter a language", customHint: "You can also enter any language directly.", showOptions: "Show all languages" }
    },
  },
  "zh-CN": {
    translation: {
      nav: { translate: "文本翻译", files: "文件翻译", history: "历史记录", glossaries: "词汇表", prompts: "提示词", providers: "AI 服务", settings: "设置", logs: "日志" },
      common: { save: "保存", cancel: "取消", delete: "删除", edit: "编辑", add: "添加", close: "关闭", import: "导入", export: "导出", name: "名称", test: "测试", testing: "测试中…", enabled: "启用", disabled: "停用", select: "选择", none: "无", ready: "就绪", error: "错误", retry: "重试", openMenu: "打开菜单", closeMenu: "关闭菜单", productSubtitle: "AI 翻译工作台", noModel: "未设置模型" },
      translate: { title: "文本翻译", subtitle: "使用指定的 AI、提示词和术语翻译内容。", source: "原文", target: "译文", sourceLanguage: "源语言", targetLanguage: "目标语言", detect: "自动检测", swapLanguages: "交换源语言和目标语言", provider: "AI 服务", prompt: "提示词", glossaries: "词汇表", reasoning: "推理程度", reasoningNone: "无", reasoningLow: "低", reasoningMedium: "中", reasoningHigh: "高", placeholder: "输入或粘贴需要翻译的内容", action: "翻译", working: "翻译中…", copy: "复制译文", copied: "已复制", characters: "{{count}} 个字符" },
      files: { title: "文件翻译", subtitle: "在格式允许时保留文档结构与排版。", drop: "将文件拖到此处，或选择文件", supported: "支持 PDF、DOCX、PPTX、XLSX、TXT、Markdown、HTML、CSV、JSON、SRT、VTT、PNG、JPG 和 WebP", choose: "选择文件", action: "翻译文件", working: "正在提交…", summarize: "翻译前先生成总结", cancel: "取消翻译", cancelling: "正在取消…", waitingForQueue: "等待文件队列", download: "下载译文", downloading: "下载中…", downloadComplete: "下载完成", savedTo: "已保存到 {{path}}", openFile: "打开文件", openFolder: "打开文件夹", mode: "输出形式", translatedOnly: "仅包含译文", bilingual: "原文 + 译文", jobs: "翻译任务", progress: "进度", queued: "排队中", preparing: "准备中", summarizing: "总结中", translating: "翻译中", packing: "正在生成文件", completed: "已完成", failed: "失败", cancelled: "已取消", segments: "片段 {{done}} / {{total}}", batches: "批次 {{done}} / {{total}}", skipped: "跳过 {{count}} 个", partialWarning: "有 {{count}} 个片段未翻译", retryFailed: "重试失败批次", retryFile: "重试文件翻译", retryFileHint: "文件翻译在生成结果前失败。", retrying: "重试中…", streaming: "实时输出", noJobs: "暂无文件任务", downloadBusy: "文件尚未完成", refresh: "刷新中" },
      glossary: { title: "词汇表", subtitle: "每次翻译可同时引用一个或多个术语集。", new: "新建词汇表", empty: "还没有词汇表", entries: "{{count}} 个术语", sourceTerm: "原词", targetTerm: "指定译法", note: "备注", addTerm: "添加术语", sourceLanguage: "源语言", targetLanguage: "目标语言" },
      prompt: { title: "提示词", subtitle: "用可复用指令控制语气、受众和输出格式。", new: "新建提示词", empty: "还没有提示词", content: "指令内容", variables: "可用变量：{{source_language}}、{{target_language}}、{{glossary}} 和 {{text}}。" },
      provider: { title: "AI 服务", subtitle: "配置兼容 OpenAI API 的 AI 服务。", new: "添加服务", type: "服务类型", baseUrl: "OpenAI 兼容 API 基础地址", model: "模型", apiKey: "API 密钥", apiKeyHint: "仅保存在本机", proxyMode: "代理", proxyNone: "不使用代理", proxySettings: "使用设置中的代理", proxySystem: "使用系统代理", images: "支持图片输入输出", connected: "服务响应正常", compatibilityHint: "请填写以 /v1 结尾的 API 基础地址，例如 http://127.0.0.1:8000/v1。文本请求同时支持 /responses 和 /chat/completions；图片生成仍需要 /responses。", reasoningParser: "推理解析器", reasoningParserAuto: "自动（根据模型名）", reasoningParserHint: "使用 vLLM 时请选择与 --reasoning-parser 相同的解析器。自动模式可识别主流 Qwen、DeepSeek、GLM、Gemma 和 Granite 模型。", discoverModels: "获取模型列表", discovering: "获取中…", contextSize: "上下文大小（tokens）", contextUnit: "tokens", contextSizeHint: "用于计算文件翻译的默认批次字符预算。", maxSegments: "单批最大片段数", segmentsUnit: "片段", maxSegmentsHint: "单次文件请求最多发送的独立片段数量。", maxConcurrent: "最大并发请求数", concurrentUnit: "并发", maxConcurrentHint: "此模型同时处理的文件请求数上限。", textTranslationModel: "文本翻译常用模型", textTranslationModelHint: "启用后，文件翻译会保留一个请求槽位给文本翻译。" },
      settings: { title: "设置", subtitle: "配置网络、界面语言、下载和本地 Web 访问。", language: "界面语言", proxy: "代理地址", proxyHint: "支持 HTTP、HTTPS、SOCKS5 和 SOCKS5H；留空时直连。", webAccess: "Web 访问", address: "监听地址", port: "端口", webHint: "Web 地址修改后需重启 Tranova。", downloads: "下载", downloadLocation: "下载位置", downloadLocationHint: "桌面版完成文件翻译后保存到这里。", sourceFolder: "原始文件所在文件夹", systemDownloads: "系统下载文件夹", customFolder: "自定义文件夹", customFolderHint: "选择自定义文件夹时使用此位置。", customFolderPlaceholder: "输入文件夹路径", chooseFolder: "选择文件夹", autoDownload: "文件翻译后自动下载", autoDownloadHint: "翻译完成后立即保存译文文件。", askDownload: "下载时询问下载位置", askDownloadHint: "保存对话框默认使用上一次选择的位置。", enabledOption: "启用", ai: "AI 请求", timeout: "AI 请求超时（秒）", timeoutHint: "非流式请求的最长等待时间，或流式响应中等待下一段数据的最长时间；每次收到数据后都会重新计时。", logging: "应用日志", loggingHint: "为日志页面保存系统事件和 AI 对话内容。", logLevel: "最低日志级别", logLevelHint: "只保存此级别及以上的消息。", version: "版本", restart: "服务器地址修改后将在重启时生效。" },
      history: { title: "翻译历史", subtitle: "查看最近的文本和文件翻译记录。", empty: "还没有翻译记录", clear: "清空历史记录", remove: "移除记录", source: "原文", translation: "译文", file: "文件", text: "文本", segments: "文件翻译" },
      logs: { title: "日志", subtitle: "查看应用事件和与 AI 的对话内容。", system: "系统日志", conversations: "AI 对话", empty: "暂无日志", success: "成功", failure: "失败", request: "请求内容", response: "返回内容" },
      status: { backendUnavailable: "Tranova 服务不可用，请启动桌面应用或服务器。", noProvider: "请先配置并启用一个 AI 服务。", saved: "已保存", imported: "导入成功" },
      languages: { en: "English", zh: "简体中文", "zh-CN": "简体中文", "zh-TW": "繁體中文", ja: "日本語", ko: "한국어", fr: "Français", de: "Deutsch", es: "Español", ru: "Русский", ar: "العربية", tlh: "tlhIngan Hol", "火星文": "吙煋呅", auto: "自动检测", customPlaceholder: "输入语言名称", customHint: "也可以直接输入任意语言名称。", showOptions: "显示全部语言" }
    },
  },
} as const;

i18n.use(initReactI18next).init({
  resources,
  lng: localStorage.getItem("tranova-language") || navigator.language,
  fallbackLng: "en",
  interpolation: { escapeValue: false },
});

export default i18n;
